import { useState, useEffect, useRef } from 'react';
import { useAuth } from '../../hooks/useAuth';
import { saveNewKnowledge, checkForDuplicates, updateLocalCache } from '../../services/knowledgeLearning';
import ChatMessage from './ChatMessage';
import LearningPrompt from './LearningPrompt';
import TypingAnimation from './TypingAnimation';

/**
 * AiChat Component
 * Main chat modal interface for users
 * Displays message history and input field
 * Integrates with aiSearch for finding answers
 * Supports self-learning when no answer is found
 */
export const AiChat = ({
  isOpen,
  onClose,
  messages,
  onSendMessage,
  loading,
  learningTriggered,
  lastUserQuestion,
  resetLearning,
}) => {
  const { currentUser, isAdmin } = useAuth();
  const [inputValue, setInputValue] = useState('');
  const [learningLoading, setLearningLoading] = useState(false);
  const [learningError, setLearningError] = useState(null);
  const [duplicateMatch, setDuplicateMatch] = useState(null);
  const [pendingAnswer, setPendingAnswer] = useState(null);
  const messagesContainerRef = useRef(null);

  // Auto-scroll to latest message and keep the view at the bottom when opened
  useEffect(() => {
    const container = messagesContainerRef.current;
    if (!container) return;

    const scrollToBottom = () => {
      container.scrollTop = container.scrollHeight;
    };

    const frame = window.requestAnimationFrame(scrollToBottom);
    return () => window.cancelAnimationFrame(frame);
  }, [isOpen, messages, loading, learningTriggered]);

  const handleSubmit = (e) => {
    e.preventDefault();
    if (inputValue.trim() && !loading) {
      onSendMessage(inputValue);
      setInputValue('');
    }
  };

  const handleLearningSubmit = async (answer) => {
    if (!lastUserQuestion || !answer.trim()) {
      setLearningError('Question and answer are required');
      return;
    }

    // Check admin permission
    if (!isAdmin) {
      setLearningError('Only admins can teach the AI');
      return;
    }

    setLearningLoading(true);
    setLearningError(null);

    try {
      // Check for duplicates
      const duplicate = await checkForDuplicates(lastUserQuestion);

      if (duplicate) {
        // Found duplicate - show warning and wait for confirmation
        setDuplicateMatch(duplicate);
        setPendingAnswer(answer); // Store answer for later use if confirmed
        setLearningLoading(false);
        return;
      }

      // No duplicate - save directly
      await performSaveKnowledge(answer);
    } catch (error) {
      console.error('Error in learning submit:', error);
      setLearningError('Failed to process learning');
      setLearningLoading(false);
    }
  };

  const performSaveKnowledge = async (answer) => {
    try {
      const result = await saveNewKnowledge(
        lastUserQuestion,
        answer,
        currentUser.uid
      );

      if (result.success) {
        // Update local cache with new knowledge
        await updateLocalCache({
          id: result.id,
          question: lastUserQuestion,
          answer: answer.trim(),
          keywords: [], // Will be generated by knowledgeLearning
          category: 'User Contributed',
          createdBy: currentUser.uid,
          createdAt: new Date(),
        });

        // Add success message to chat
        setInputValue('');
        setDuplicateMatch(null);
        setPendingAnswer(null);
        resetLearning();

        // Show success feedback
        setLearningError(null);
      } else {
        setLearningError(result.error || 'Failed to save');
      }
    } catch (error) {
      console.error('Error saving knowledge:', error);
      setLearningError('Failed to save');
    } finally {
      setLearningLoading(false);
    }
  };

  const handleConfirmDuplicate = async () => {
    if (!pendingAnswer) {
      setLearningError('Answer not found');
      return;
    }

    setLearningLoading(true);
    setLearningError(null);

    // Override duplicate warning and save anyway
    await performSaveKnowledge(pendingAnswer);
  };

  const handleLearningCancel = () => {
    setLearningError(null);
    setDuplicateMatch(null);
    resetLearning();
  };

  if (!isOpen) return null;

  return (
    <>
      {/* Chat Modal (no backdrop - only the widget is shown) */}
      <div
        className="fixed bottom-24 right-6 w-96 max-h-[550px] bg-white rounded-lg shadow-2xl flex flex-col z-50 animate-slide-up hidden sm:flex"
        onClick={(e) => e.stopPropagation()}
      >
        {/* Header */}
        <div className="bg-blue-600 text-white px-4 py-3 rounded-t-lg flex items-center justify-between">
          <div className="flex items-center gap-2">
            <div className="w-2 h-2 rounded-full bg-green-400 animate-pulse"></div>
            <h3 className="font-semibold text-sm">AI Support Assistant</h3>
          </div>
          <button
            onClick={onClose}
            className="text-white hover:bg-blue-700 rounded p-1 transition-colors"
            aria-label="Close chat"
          >
            <svg
              className="w-5 h-5"
              fill="currentColor"
              viewBox="0 0 20 20"
            >
              <path
                fillRule="evenodd"
                d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z"
                clipRule="evenodd"
              ></path>
            </svg>
          </button>
        </div>

        {/* Messages Container */}
        <div ref={messagesContainerRef} className="flex-1 overflow-y-auto p-4 bg-gray-50">
          {messages.length === 0 && !learningTriggered ? (
            <div className="flex flex-col items-center justify-center h-full text-center">
              <div className="text-4xl mb-2">👋</div>
              <p className="text-sm text-gray-600 mb-2">Hi! I'm your AI Assistant</p>
              <p className="text-xs text-gray-500">
                Ask me anything about your support topics
              </p>
            </div>
          ) : (
            <>
              {messages.map((message) => (
                <ChatMessage key={message.id} message={message} />
              ))}
              
              {/* Learning Mode - Show when no answer found */}
              {learningTriggered && lastUserQuestion && !isAdmin && (
                <div className="mt-4 p-3 bg-blue-50 border border-blue-200 rounded-lg text-sm text-gray-700">
                  <p className="font-semibold mb-1">📚 Learning Mode</p>
                  <p className="text-xs">
                    Only admins can teach me new answers. Please ask an admin to help improve my knowledge!
                  </p>
                </div>
              )}

              {learningTriggered && lastUserQuestion && isAdmin && (
                <LearningPrompt
                  question={lastUserQuestion}
                  onSave={handleLearningSubmit}
                  onCancel={handleLearningCancel}
                  loading={learningLoading}
                  isDuplicate={duplicateMatch}
                  onConfirmDuplicate={handleConfirmDuplicate}
                />
              )}

              {loading && <TypingAnimation />}
            </>
          )}
        </div>

        {/* Input Form - Hidden during learning */}
        {!learningTriggered && (
          <form
            onSubmit={handleSubmit}
            className="border-t border-gray-200 p-3 bg-white rounded-b-lg"
          >
            <div className="flex gap-2">
              <input
                type="text"
                value={inputValue}
                onChange={(e) => setInputValue(e.target.value)}
                placeholder="Type your question..."
                disabled={loading}
                className="flex-1 px-3 py-2 border border-gray-300 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-blue-500 disabled:bg-gray-100 disabled:text-gray-500"
                autoComplete="off"
              />
              <button
                type="submit"
                disabled={loading || !inputValue.trim()}
                className="px-3 py-2 bg-blue-600 text-white rounded-lg text-sm font-medium hover:bg-blue-700 disabled:bg-gray-400 disabled:cursor-not-allowed transition-colors"
                aria-label="Send message"
              >
                {loading ? (
                  <svg
                    className="w-4 h-4 animate-spin"
                    fill="none"
                    viewBox="0 0 24 24"
                    stroke="currentColor"
                  >
                    <circle
                      className="opacity-25"
                      cx="12"
                      cy="12"
                      r="10"
                      stroke="currentColor"
                      strokeWidth="4"
                    ></circle>
                    <path
                      className="opacity-75"
                      fill="currentColor"
                      d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"
                    ></path>
                  </svg>
                ) : (
                  <svg
                    className="w-4 h-4"
                    fill="currentColor"
                    viewBox="0 0 20 20"
                  >
                    <path d="M10.894 2.553a1 1 0 00-1.788 0l-7 14a1 1 0 001.169 1.409l5.951-1.429 5.951 1.429a1 1 0 001.169-1.409l-7-14z"></path>
                  </svg>
                )}
              </button>
            </div>
          </form>
        )}
      </div>
    </>
  );
};

export default AiChat;
